theme: jekyll-theme-cayman
title: Michał Stobierski
description: Theoretical Computer Science Student · Software Engineer · Kraków, Poland
urls:
  cv: /assets
  github: https://github.com/stobis
  linkedin: https://www.linkedin.com/in/michal-stobierski/
